sudo: false
language: node_js
addons:
  apt:
    packages:
    - rabbitmq-server
node_js:
  - '8'
  - '10'
  - '12'
before_install:
  - npm i npminstall -g
install:
  - npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
